added ivy's details
muokicaleb/KamiLimu_6.0_git102 pull request #10
Opened 2022-02-14 17:32 UTC by Ivy8127

Added my details to the page
I also forgot to create a branch and got lazy ...

2022-02-15 08:31 UTC, RuthNjeri commented on index.html
> +                  <a href="#"><i class="bi bi-instagram"></i></a>
If the links are not present, remove the tags.
```suggestion

```

2022-02-15 08:35 UTC, RuthNjeri commented on index.html
> +                <span>Software Engineer</span>
This code should be after line 662 below, in the row div

2022-02-15 08:36 UTC, RuthNjeri requested changes
Good first attempt @Ivy8127! The image should be 600 by 600 pixels. Also, is there an image named `team-5` in the assets? I cannot see it in the file changes.

2022-03-05 18:49 UTC, RuthNjeri commented
Hi @Ivy8127, did you look at the comments above?

2022-03-07 13:37 UTC, Ivy8127 commented
> Hi @Ivy8127, did you look at the comments above?

Hi, @RuthNjeri  I've made corrections to the comments you made. About the width and height, the width and height style attributes aren't changing to 600 px though when I locally view the image. Is it the bootstrap? How do I change that?

2022-03-14 07:15 UTC, RuthNjeri commented
Hi @Ivy8127, can you share a screenshot of what's happening on your end?

2022-03-17 17:26 UTC, Ivy8127 commented
> Hi @Ivy8127, can you share a screenshot of what's happening on your end?

@RuthNjeri  Sure : [
![image](https://user-images.githubusercontent.com/55692389/158859120-f17e89b0-1d82-45de-a525-66dd23862982.png)
](url)

2022-03-22 08:09 UTC, RuthNjeri commented
Hi Ivy, what would happen if you use inline styling and add the ! important rule?

2022-03-27 17:24 UTC, RuthNjeri commented
Feedback implementation took too long. Closing the PR.

2022-03-27 17:24 UTC, closed without merging