add new team member
muokicaleb/KamiLimu_6.0_git102 pull request #12
Opened 2022-02-16 11:52 UTC by Japhetb

Add new team member profile

2022-02-21 07:52 UTC, RuthNjeri commented on index.html
> -            <!--machoguabednego6@gmail.com	-->
You were supposed to include your code beneath the commented line of your name and not remove anyone else's name...

2022-02-21 07:53 UTC, RuthNjeri commented on index.html
> +                  <span>Accountant</span>
There are no links to your profile and the name and job title is not related to you... you need to fill in this section with your details.

2022-02-21 07:53 UTC, RuthNjeri requested changes

2022-02-21 07:53 UTC, RuthNjeri commented on index.html
> +                  <img src="assets/img/team/steve.jpeg" class="img-fluid" alt="">
The picture should be of dimensions 600 pixels to 600 pixels, width and height.

2022-03-05 18:50 UTC, RuthNjeri commented
Hi @Japhetb, did you look at the comments above?

2022-03-06 08:11 UTC, Japhetb commented
> 

On it

2022-03-14 07:13 UTC, RuthNjeri commented
Hi @Japhetb , still working on this?

2022-03-27 17:23 UTC, RuthNjeri commented
Feedback implementation took too long. Closing the PR.

2022-03-27 17:23 UTC, closed without merging