Add Machogu Details to Team section
muokicaleb/KamiLimu_6.0_git102 pull request #7
Opened 2022-02-11 07:25 UTC by AbedM15

Added Machogu's details and links to Team section

2022-02-11 16:15 UTC, muokicaleb commented
Could you change the image dimensions to 600x600

2022-02-13 04:21 UTC, AbedM15 commented
Done. On my local branch then uploaded to my remote branch. Will I have to
create a new PR for the new changes?

On Fri, 11 Feb 2022 at 19:15, Muoki Caleb ***@***.***> wrote:

> Could you change the image dimensions to 600x600
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/muokicaleb/KamiLimu_6.0_git102/pull/7#issuecomment-1036377228>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALG3646TMG2TQLY544H3HKTU2UY3JANCNFSM5ODLG3KQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-02-15 08:27 UTC, RuthNjeri commented on index.html
> +                  </div>
Is this code supposed to be inside the row div from line 697 below? Ideally where you have removed your name? see suggestion below
```suggestion
```

2022-02-15 08:27 UTC, RuthNjeri commented on index.html
> +
```suggestion
              <!--machoguabednego6@gmail.com	-->
              <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
                <div class="member" data-aos="fade-up" data-aos-delay="200">
                  <div class="member-img">
                    <img src="assets/img/team/Machogu.jpeg" class="img-fluid" alt="Machogu's image" width="600" height="600">
                    <div class="social">
                      <a href="https://twitter.com/Machogu_"><i class="bi bi-twitter"></i></a>
                      <a href=""><i class="bi bi-facebook"></i></a>
                      <a href=""><i class="bi bi-instagram"></i></a>
                      <a href="https://www.linkedin.com/in/abednego-machogu-805841215/"><i class="bi bi-linkedin"></i></a>
                    </div>
                  </div>
                  <div class="member-info">
                    <h4>Machogu</h4>
                    <span>Software Engineer</span>
                  </div>
```

2022-02-15 08:27 UTC, RuthNjeri requested changes
Good first attempt @AbedM15! There are files on the PR that should not be present like the `.DS_Store`

2022-02-15 08:27 UTC, RuthNjeri commented
Let us know if you need any assistance.

2022-03-05 18:48 UTC, RuthNjeri commented
Hi @AbedM15, were you able to look at the comments above?

2022-03-07 13:49 UTC, AbedM15 commented
Hello,

Apologies for the delay but I have finally made the changes as required I
believe.

On Sat, 5 Mar 2022 at 21:48, Ruth ***@***.***> wrote:

> Hi @AbedM15 <https://github.com/AbedM15>, were you able to look at the
> comments above?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/muokicaleb/KamiLimu_6.0_git102/pull/7#issuecomment-1059814016>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALG3647347ZZIGNM3WRUSFTU6OUALANCNFSM5ODLG3KQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-14 07:17 UTC, RuthNjeri commented
Hi @AbedM15, I have seen the changes, perhaps you could remove changes not related to this PR? Like these files

<img width="581" alt="Screenshot 2022-03-14 at 10 14 12" src="https://user-images.githubusercontent.com/7622875/158122950-daa484f6-3253-42e0-abb8-d3a18b07eccb.png">

Also, you can look into fixing merge conflicts since your PR has one.

2022-03-24 09:01 UTC, AbedM15 commented
I have removed all .DS_Store files from the folder.

2022-03-27 17:09 UTC, RuthNjeri commented
Funny photo! The PR looks good to me!

2022-03-27 17:09 UTC, merged